/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pecl3_2;
import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author FERNANDO
 */
public class Main extends javax.swing.JFrame {
    Parque p;
    CreaUsuarios generadorUsuarios;
    
    ServerSocket servidor;
    Socket conexion;
    DataInputStream entrada;
    DataOutputStream salida;
    int nConexion = 0;
    Hilopeticiones hiloConexiones;

    /**
     * Creates new form MainPrueba
     */
    public Main() {
        initComponents();
        Color color= new Color(0,153,204);
        this.setTitle("Parque Acuático Slide & Splash");
        this.getContentPane().setBackground(color);

           p= new Parque(jTextIDsColaEntrada, jTextIDsColaVestuario, jTextIDsVestuario,
                        jSpinnerIDsColaEntrada,jSpinnerIDsColaVestuario,jSpinnerIDsVestuario,
                      jTextIDsColaTumbonas, jSpinnerIDsColaTumbonas, jTextIDsZonaTumbonas1,
                        jSpinnerIDsZonaTumbonas,
                        jTextIDsColaPiscinaOlas, jTextIDsZonaPiscinaOlas , jSpinnerIDsColaPiscinaOlas , jSpinnerIDsZonaPiscinaOlas,
                      jTextIDsColaPiscinaNiños,jTextIDsZonaPiscinaNiños,jTextIDsZonaEsperaPiscinaNiños,
                        jSpinnerIDsColaPiscinaNiños,jSpinnerIDsZonaPiscinaNiños,jSpinnerIDsZonaEsperaPiscinaNiños,
                        jTextIDsColaPiscinaGrande,jTextIDsZonaPiscinaGrande,jTextIDsColaPiscinaGrande1,jTextIDsColaPiscinaGrande2,jTextIDsColaPiscinaGrande3,
                    jSpinnerIDsColaPiscinaGrande,jSpinnerIDsZonaPiscinaGrande,jSpinnerIDsColaPiscinaGrande1,jSpinnerIDsColaPiscinaGrande2,jSpinnerIDsColaPiscinaGrande3,
                        jTextFieldToboganA,jTextFieldToboganB,jTextFieldToboganC,
                    jTextFieldMonitorV,jTextFieldMonitorTB,jTextFieldMonitorPO,jTextFieldMonitorPN,jTextFieldMonitorPG,jTextFieldMonitorToboganA,jTextFieldMonitorToboganB,jTextFieldMonitorToboganC);
    
        generadorUsuarios= new CreaUsuarios(p, 1000);
        /*     for (int i = 1; i <= 100; i++) {
            Usuario u = new Usuario(i, p);
            if (u.isAcompañado() && !u.isAdulto()) {
                i++;
                UsuarioAcompañante acompañante = new UsuarioAcompañante(i, p);                                 //creacion del acompañante con el segundo constructor
                u.setUsuarioAcompañante(acompañante);
                acompañante.start();
            }
                u.start();
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
            }
        }   */
            generadorUsuarios.start();
        try {
            hiloConexiones= new Hilopeticiones(3, 4000,jTextFieldConexiones,p);
        } catch (IOException ex) {
        }
            hiloConexiones.start(); 
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelColaEntrada = new javax.swing.JPanel();
        jTextIDsColaEntrada = new javax.swing.JTextField();
        jSpinnerIDsColaEntrada = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jPanelColaVestuario = new javax.swing.JPanel();
        jTextIDsColaVestuario = new javax.swing.JTextField();
        jSpinnerIDsColaVestuario = new javax.swing.JSpinner();
        jPanelVestuario = new javax.swing.JPanel();
        jTextIDsVestuario = new javax.swing.JTextField();
        jSpinnerIDsVestuario = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldMonitorV = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanelColaTumbonas = new javax.swing.JPanel();
        jTextIDsColaTumbonas = new javax.swing.JTextField();
        jSpinnerIDsColaTumbonas = new javax.swing.JSpinner();
        jPanelZonaTumbonas = new javax.swing.JPanel();
        jTextIDsZonaTumbonas1 = new javax.swing.JTextField();
        jSpinnerIDsZonaTumbonas = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMonitorTB = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanelColaPiscinaNiños = new javax.swing.JPanel();
        jTextIDsColaPiscinaNiños = new javax.swing.JTextField();
        jSpinnerIDsColaPiscinaNiños = new javax.swing.JSpinner();
        jPanelZonaPiscinaNiños = new javax.swing.JPanel();
        jTextIDsZonaPiscinaNiños = new javax.swing.JTextField();
        jSpinnerIDsZonaPiscinaNiños = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextIDsZonaEsperaPiscinaNiños = new javax.swing.JTextField();
        jSpinnerIDsZonaEsperaPiscinaNiños = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldMonitorPN = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextIDsColaPiscinaGrande1 = new javax.swing.JTextField();
        jSpinnerIDsColaPiscinaGrande1 = new javax.swing.JSpinner();
        jTextIDsColaPiscinaGrande2 = new javax.swing.JTextField();
        jSpinnerIDsColaPiscinaGrande2 = new javax.swing.JSpinner();
        jTextIDsColaPiscinaGrande3 = new javax.swing.JTextField();
        jSpinnerIDsColaPiscinaGrande3 = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldToboganA = new javax.swing.JTextField();
        jTextFieldToboganB = new javax.swing.JTextField();
        jTextFieldToboganC = new javax.swing.JTextField();
        jTextFieldMonitorToboganA = new javax.swing.JTextField();
        jTextFieldMonitorToboganB = new javax.swing.JTextField();
        jTextFieldMonitorToboganC = new javax.swing.JTextField();
        jPanelColaPiscinaGrande = new javax.swing.JPanel();
        jTextIDsColaPiscinaGrande = new javax.swing.JTextField();
        jSpinnerIDsColaPiscinaGrande = new javax.swing.JSpinner();
        jPanelZonaTumbonas1 = new javax.swing.JPanel();
        jTextIDsZonaPiscinaGrande = new javax.swing.JTextField();
        jSpinnerIDsZonaPiscinaGrande = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldMonitorPG = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jButtonPararReanudar = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        jPanelColaPiscinaOlas = new javax.swing.JPanel();
        jTextIDsColaPiscinaOlas = new javax.swing.JTextField();
        jSpinnerIDsColaPiscinaOlas = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jPanelZonaPiscinaOlas = new javax.swing.JPanel();
        jTextIDsZonaPiscinaOlas = new javax.swing.JTextField();
        jSpinnerIDsZonaPiscinaOlas = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldMonitorPO = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextFieldConexiones = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 204));

        jPanelColaEntrada.setBackground(new java.awt.Color(0, 204, 204));

        jTextIDsColaEntrada.setEditable(false);
        jTextIDsColaEntrada.setToolTipText("");

        jSpinnerIDsColaEntrada.setAlignmentX(200.0F);
        jSpinnerIDsColaEntrada.setAlignmentY(200.0F);
        jSpinnerIDsColaEntrada.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaEntrada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaEntradaStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Cola Entrada");

        javax.swing.GroupLayout jPanelColaEntradaLayout = new javax.swing.GroupLayout(jPanelColaEntrada);
        jPanelColaEntrada.setLayout(jPanelColaEntradaLayout);
        jPanelColaEntradaLayout.setHorizontalGroup(
            jPanelColaEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaEntradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelColaEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsColaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsColaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
            .addGroup(jPanelColaEntradaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelColaEntradaLayout.setVerticalGroup(
            jPanelColaEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaEntradaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColaEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsColaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsColaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelColaVestuario.setBackground(new java.awt.Color(0, 204, 204));

        jTextIDsColaVestuario.setEditable(false);
        jTextIDsColaVestuario.setToolTipText("");

        jSpinnerIDsColaVestuario.setAlignmentX(200.0F);
        jSpinnerIDsColaVestuario.setAlignmentY(200.0F);
        jSpinnerIDsColaVestuario.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaVestuario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaVestuarioStateChanged(evt);
            }
        });

        jPanelVestuario.setOpaque(false);

        jTextIDsVestuario.setEditable(false);
        jTextIDsVestuario.setToolTipText("");
        jTextIDsVestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDsVestuarioActionPerformed(evt);
            }
        });

        jSpinnerIDsVestuario.setAlignmentX(200.0F);
        jSpinnerIDsVestuario.setAlignmentY(200.0F);
        jSpinnerIDsVestuario.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsVestuario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsVestuarioStateChanged(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Vestuario");

        javax.swing.GroupLayout jPanelVestuarioLayout = new javax.swing.GroupLayout(jPanelVestuario);
        jPanelVestuario.setLayout(jPanelVestuarioLayout);
        jPanelVestuarioLayout.setHorizontalGroup(
            jPanelVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVestuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
            .addGroup(jPanelVestuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVestuarioLayout.setVerticalGroup(
            jPanelVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVestuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Cola Vestuario");

        jTextFieldMonitorV.setEditable(false);
        jTextFieldMonitorV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonitorVActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Monitor");

        javax.swing.GroupLayout jPanelColaVestuarioLayout = new javax.swing.GroupLayout(jPanelColaVestuario);
        jPanelColaVestuario.setLayout(jPanelColaVestuarioLayout);
        jPanelColaVestuarioLayout.setHorizontalGroup(
            jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaVestuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextIDsColaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerIDsColaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelColaVestuarioLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(206, 206, 206))
                    .addComponent(jPanelVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColaVestuarioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMonitorV, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelColaVestuarioLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel22)))
                .addGap(460, 460, 460))
        );
        jPanelColaVestuarioLayout.setVerticalGroup(
            jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaVestuarioLayout.createSequentialGroup()
                .addGroup(jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColaVestuarioLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel15))
                    .addGroup(jPanelColaVestuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColaVestuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsColaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsColaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonitorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelColaTumbonas.setBackground(new java.awt.Color(0, 204, 204));

        jTextIDsColaTumbonas.setEditable(false);
        jTextIDsColaTumbonas.setToolTipText("");

        jSpinnerIDsColaTumbonas.setAlignmentX(200.0F);
        jSpinnerIDsColaTumbonas.setAlignmentY(200.0F);
        jSpinnerIDsColaTumbonas.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaTumbonas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaTumbonasStateChanged(evt);
            }
        });

        jPanelZonaTumbonas.setOpaque(false);

        jTextIDsZonaTumbonas1.setEditable(false);
        jTextIDsZonaTumbonas1.setToolTipText("");

        jSpinnerIDsZonaTumbonas.setAlignmentX(200.0F);
        jSpinnerIDsZonaTumbonas.setAlignmentY(200.0F);
        jSpinnerIDsZonaTumbonas.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsZonaTumbonas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsZonaTumbonasStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("ZonaTumbonas");

        javax.swing.GroupLayout jPanelZonaTumbonasLayout = new javax.swing.GroupLayout(jPanelZonaTumbonas);
        jPanelZonaTumbonas.setLayout(jPanelZonaTumbonasLayout);
        jPanelZonaTumbonasLayout.setHorizontalGroup(
            jPanelZonaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZonaTumbonasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelZonaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsZonaTumbonas1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsZonaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
            .addGroup(jPanelZonaTumbonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelZonaTumbonasLayout.setVerticalGroup(
            jPanelZonaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaTumbonasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZonaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsZonaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsZonaTumbonas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("ColaTumbonas");

        jTextFieldMonitorTB.setEditable(false);
        jTextFieldMonitorTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonitorTBActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Monitor");

        javax.swing.GroupLayout jPanelColaTumbonasLayout = new javax.swing.GroupLayout(jPanelColaTumbonas);
        jPanelColaTumbonas.setLayout(jPanelColaTumbonasLayout);
        jPanelColaTumbonasLayout.setHorizontalGroup(
            jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                .addComponent(jPanelZonaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIDsColaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerIDsColaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMonitorTB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel25)))
                .addGap(520, 520, 520))
        );
        jPanelColaTumbonasLayout.setVerticalGroup(
            jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelColaTumbonasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerIDsColaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIDsColaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelColaTumbonasLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMonitorTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelZonaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelColaPiscinaNiños.setBackground(new java.awt.Color(0, 204, 204));

        jTextIDsColaPiscinaNiños.setEditable(false);
        jTextIDsColaPiscinaNiños.setToolTipText("");

        jSpinnerIDsColaPiscinaNiños.setAlignmentX(200.0F);
        jSpinnerIDsColaPiscinaNiños.setAlignmentY(200.0F);
        jSpinnerIDsColaPiscinaNiños.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaPiscinaNiños.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaPiscinaNiñosStateChanged(evt);
            }
        });

        jPanelZonaPiscinaNiños.setOpaque(false);

        jTextIDsZonaPiscinaNiños.setEditable(false);
        jTextIDsZonaPiscinaNiños.setToolTipText("");

        jSpinnerIDsZonaPiscinaNiños.setAlignmentX(200.0F);
        jSpinnerIDsZonaPiscinaNiños.setAlignmentY(200.0F);
        jSpinnerIDsZonaPiscinaNiños.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsZonaPiscinaNiños.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsZonaPiscinaNiñosStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Zona Piscina Niños");

        javax.swing.GroupLayout jPanelZonaPiscinaNiñosLayout = new javax.swing.GroupLayout(jPanelZonaPiscinaNiños);
        jPanelZonaPiscinaNiños.setLayout(jPanelZonaPiscinaNiñosLayout);
        jPanelZonaPiscinaNiñosLayout.setHorizontalGroup(
            jPanelZonaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZonaPiscinaNiñosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelZonaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsZonaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsZonaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
            .addGroup(jPanelZonaPiscinaNiñosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelZonaPiscinaNiñosLayout.setVerticalGroup(
            jPanelZonaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaPiscinaNiñosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZonaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsZonaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsZonaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextIDsZonaEsperaPiscinaNiños.setEditable(false);
        jTextIDsZonaEsperaPiscinaNiños.setToolTipText("");

        jSpinnerIDsZonaEsperaPiscinaNiños.setAlignmentX(200.0F);
        jSpinnerIDsZonaEsperaPiscinaNiños.setAlignmentY(200.0F);
        jSpinnerIDsZonaEsperaPiscinaNiños.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsZonaEsperaPiscinaNiños.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsZonaEsperaPiscinaNiñosStateChanged(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Cola Piscina Niños");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Zona Espera Piscina Niños");

        jTextFieldMonitorPN.setEditable(false);
        jTextFieldMonitorPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonitorPNActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Monitor");

        javax.swing.GroupLayout jPanelColaPiscinaNiñosLayout = new javax.swing.GroupLayout(jPanelColaPiscinaNiños);
        jPanelColaPiscinaNiños.setLayout(jPanelColaPiscinaNiñosLayout);
        jPanelColaPiscinaNiñosLayout.setHorizontalGroup(
            jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                .addComponent(jPanelZonaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextIDsZonaEsperaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsZonaEsperaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                        .addGroup(jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIDsColaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerIDsColaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMonitorPN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel24)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelColaPiscinaNiñosLayout.setVerticalGroup(
            jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerIDsColaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIDsColaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelColaPiscinaNiñosLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMonitorPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelZonaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelColaPiscinaNiñosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsZonaEsperaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsZonaEsperaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Colas Toboganes");

        jTextIDsColaPiscinaGrande1.setEditable(false);
        jTextIDsColaPiscinaGrande1.setToolTipText("");

        jSpinnerIDsColaPiscinaGrande1.setAlignmentX(200.0F);
        jSpinnerIDsColaPiscinaGrande1.setAlignmentY(200.0F);
        jSpinnerIDsColaPiscinaGrande1.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaPiscinaGrande1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaPiscinaGrande1StateChanged(evt);
            }
        });

        jTextIDsColaPiscinaGrande2.setEditable(false);
        jTextIDsColaPiscinaGrande2.setToolTipText("");

        jSpinnerIDsColaPiscinaGrande2.setAlignmentX(200.0F);
        jSpinnerIDsColaPiscinaGrande2.setAlignmentY(200.0F);
        jSpinnerIDsColaPiscinaGrande2.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaPiscinaGrande2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaPiscinaGrande2StateChanged(evt);
            }
        });

        jTextIDsColaPiscinaGrande3.setEditable(false);
        jTextIDsColaPiscinaGrande3.setToolTipText("");

        jSpinnerIDsColaPiscinaGrande3.setAlignmentX(200.0F);
        jSpinnerIDsColaPiscinaGrande3.setAlignmentY(200.0F);
        jSpinnerIDsColaPiscinaGrande3.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaPiscinaGrande3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaPiscinaGrande3StateChanged(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("A");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("B");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("C");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText(" Tobogan ");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Monitor Tobogan");

        jTextFieldToboganA.setEditable(false);
        jTextFieldToboganA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToboganAActionPerformed(evt);
            }
        });

        jTextFieldToboganB.setEditable(false);
        jTextFieldToboganB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToboganBActionPerformed(evt);
            }
        });

        jTextFieldToboganC.setEditable(false);
        jTextFieldToboganC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToboganCActionPerformed(evt);
            }
        });

        jTextFieldMonitorToboganA.setEditable(false);
        jTextFieldMonitorToboganA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonitorToboganAActionPerformed(evt);
            }
        });

        jTextFieldMonitorToboganB.setEditable(false);

        jTextFieldMonitorToboganC.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextIDsColaPiscinaGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerIDsColaPiscinaGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIDsColaPiscinaGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerIDsColaPiscinaGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIDsColaPiscinaGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerIDsColaPiscinaGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldMonitorToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldMonitorToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldMonitorToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsColaPiscinaGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsColaPiscinaGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonitorToboganA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsColaPiscinaGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsColaPiscinaGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonitorToboganB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsColaPiscinaGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsColaPiscinaGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jTextFieldToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMonitorToboganC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelColaPiscinaGrande.setBackground(new java.awt.Color(0, 204, 204));

        jTextIDsColaPiscinaGrande.setEditable(false);
        jTextIDsColaPiscinaGrande.setToolTipText("");

        jSpinnerIDsColaPiscinaGrande.setAlignmentX(200.0F);
        jSpinnerIDsColaPiscinaGrande.setAlignmentY(200.0F);
        jSpinnerIDsColaPiscinaGrande.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaPiscinaGrande.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaPiscinaGrandeStateChanged(evt);
            }
        });

        jPanelZonaTumbonas1.setOpaque(false);

        jTextIDsZonaPiscinaGrande.setEditable(false);
        jTextIDsZonaPiscinaGrande.setToolTipText("");

        jSpinnerIDsZonaPiscinaGrande.setAlignmentX(200.0F);
        jSpinnerIDsZonaPiscinaGrande.setAlignmentY(200.0F);
        jSpinnerIDsZonaPiscinaGrande.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsZonaPiscinaGrande.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsZonaPiscinaGrandeStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("ZonaPiscinaGrande");

        javax.swing.GroupLayout jPanelZonaTumbonas1Layout = new javax.swing.GroupLayout(jPanelZonaTumbonas1);
        jPanelZonaTumbonas1.setLayout(jPanelZonaTumbonas1Layout);
        jPanelZonaTumbonas1Layout.setHorizontalGroup(
            jPanelZonaTumbonas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZonaTumbonas1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelZonaTumbonas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsZonaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsZonaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
            .addGroup(jPanelZonaTumbonas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelZonaTumbonas1Layout.setVerticalGroup(
            jPanelZonaTumbonas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaTumbonas1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelZonaTumbonas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsZonaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsZonaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("ColaPiscinaGrande");

        jTextFieldMonitorPG.setEditable(false);
        jTextFieldMonitorPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonitorPGActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Monitor");

        javax.swing.GroupLayout jPanelColaPiscinaGrandeLayout = new javax.swing.GroupLayout(jPanelColaPiscinaGrande);
        jPanelColaPiscinaGrande.setLayout(jPanelColaPiscinaGrandeLayout);
        jPanelColaPiscinaGrandeLayout.setHorizontalGroup(
            jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaPiscinaGrandeLayout.createSequentialGroup()
                .addComponent(jPanelZonaTumbonas1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelColaPiscinaGrandeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextIDsColaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerIDsColaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldMonitorPG, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelColaPiscinaGrandeLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel26)))
                .addGap(520, 520, 520))
        );
        jPanelColaPiscinaGrandeLayout.setVerticalGroup(
            jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaPiscinaGrandeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColaPiscinaGrandeLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMonitorPG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelColaPiscinaGrandeLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelColaPiscinaGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerIDsColaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIDsColaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jPanelZonaTumbonas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(0, 153, 204));

        jButtonPararReanudar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPararReanudar.setText("PARAR");
        jButtonPararReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararReanudarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPararReanudar, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jButtonPararReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        titulo.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        titulo.setText("PARQUE ACUÁTICO SLIDE & SPLASH");

        jPanelColaPiscinaOlas.setBackground(new java.awt.Color(0, 204, 204));

        jTextIDsColaPiscinaOlas.setEditable(false);
        jTextIDsColaPiscinaOlas.setToolTipText("");

        jSpinnerIDsColaPiscinaOlas.setAlignmentX(200.0F);
        jSpinnerIDsColaPiscinaOlas.setAlignmentY(200.0F);
        jSpinnerIDsColaPiscinaOlas.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsColaPiscinaOlas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsColaPiscinaOlasStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Zona Piscina Olas");

        jPanelZonaPiscinaOlas.setOpaque(false);

        jTextIDsZonaPiscinaOlas.setEditable(false);
        jTextIDsZonaPiscinaOlas.setToolTipText("");

        jSpinnerIDsZonaPiscinaOlas.setAlignmentX(200.0F);
        jSpinnerIDsZonaPiscinaOlas.setAlignmentY(200.0F);
        jSpinnerIDsZonaPiscinaOlas.setNextFocusableComponent(jTextIDsColaEntrada);
        jSpinnerIDsZonaPiscinaOlas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerIDsZonaPiscinaOlasStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelZonaPiscinaOlasLayout = new javax.swing.GroupLayout(jPanelZonaPiscinaOlas);
        jPanelZonaPiscinaOlas.setLayout(jPanelZonaPiscinaOlasLayout);
        jPanelZonaPiscinaOlasLayout.setHorizontalGroup(
            jPanelZonaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelZonaPiscinaOlasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelZonaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsZonaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsZonaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
        );
        jPanelZonaPiscinaOlasLayout.setVerticalGroup(
            jPanelZonaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelZonaPiscinaOlasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelZonaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerIDsZonaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIDsZonaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Cola Piscina Olas");

        jTextFieldMonitorPO.setEditable(false);
        jTextFieldMonitorPO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMonitorPOActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Monitor");

        javax.swing.GroupLayout jPanelColaPiscinaOlasLayout = new javax.swing.GroupLayout(jPanelColaPiscinaOlas);
        jPanelColaPiscinaOlas.setLayout(jPanelColaPiscinaOlasLayout);
        jPanelColaPiscinaOlasLayout.setHorizontalGroup(
            jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelColaPiscinaOlasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextIDsColaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIDsColaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(611, 611, 611))
            .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                .addComponent(jPanelZonaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addGroup(jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMonitorPO, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel23)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelColaPiscinaOlasLayout.setVerticalGroup(
            jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                .addGroup(jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(7, 7, 7)
                        .addGroup(jPanelColaPiscinaOlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerIDsColaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIDsColaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelColaPiscinaOlasLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMonitorPO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(2, 2, 2)
                .addComponent(jPanelZonaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldConexiones.setEditable(false);
        jTextFieldConexiones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldConexiones.setText("0");

        jLabel6.setText("Conexiones Simultaneas :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelColaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelColaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(274, 274, 274)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelColaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelColaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelColaPiscinaNiños, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelColaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, 519, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldConexiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelColaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelColaTumbonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanelColaPiscinaNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelColaVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jPanelColaPiscinaOlas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jPanelColaPiscinaGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerIDsColaEntradaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaEntradaStateChanged

       int x=(int) jSpinnerIDsColaEntrada.getValue();
       p.mostrarIDSColaEntrada(x);
    

// TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerIDsColaEntradaStateChanged

    private void jSpinnerIDsColaVestuarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaVestuarioStateChanged
        // TODO add your handling code here:
       int x=(int) jSpinnerIDsColaVestuario.getValue();
        p.mostrarIDSColaEntradaVestuarios(x);
  
    }//GEN-LAST:event_jSpinnerIDsColaVestuarioStateChanged

    private void jSpinnerIDsVestuarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsVestuarioStateChanged
        // TODO add your handling code here:
    
        int x=(int) jSpinnerIDsVestuario.getValue();
        p.mostrarIDSVestuarios(x);
   
    }//GEN-LAST:event_jSpinnerIDsVestuarioStateChanged

    private void jSpinnerIDsColaTumbonasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaTumbonasStateChanged
        // TODO add your handling code here:
  
       int x=(int) jSpinnerIDsColaTumbonas.getValue();
        p.mostrarIDSColaTumbonas(x);

    }//GEN-LAST:event_jSpinnerIDsColaTumbonasStateChanged

    private void jTextIDsVestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDsVestuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDsVestuarioActionPerformed

    private void jSpinnerIDsZonaTumbonasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsZonaTumbonasStateChanged
        // TODO add your handling code here:
       
        int x=(int) jSpinnerIDsZonaTumbonas.getValue();
        p.mostrarIDSZonaTumbonas(x);
        
    }//GEN-LAST:event_jSpinnerIDsZonaTumbonasStateChanged

    private void jSpinnerIDsColaPiscinaOlasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaPiscinaOlasStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsColaPiscinaOlas.getValue();
        p.mostrarIDSColaPiscinaOlas(x);
    }//GEN-LAST:event_jSpinnerIDsColaPiscinaOlasStateChanged

    private void jSpinnerIDsZonaPiscinaOlasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsZonaPiscinaOlasStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsZonaPiscinaOlas.getValue();
        p.mostrarIDSZonaPiscinaOlas(x);
    }//GEN-LAST:event_jSpinnerIDsZonaPiscinaOlasStateChanged

    private void jSpinnerIDsColaPiscinaNiñosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaPiscinaNiñosStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsColaPiscinaNiños.getValue();
        p.mostrarIDSColaPiscinaNiños(x);
    }//GEN-LAST:event_jSpinnerIDsColaPiscinaNiñosStateChanged

    private void jSpinnerIDsZonaPiscinaNiñosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsZonaPiscinaNiñosStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsZonaPiscinaNiños.getValue();
        p.mostrarIDSZonaPiscinaNiños(x);
    }//GEN-LAST:event_jSpinnerIDsZonaPiscinaNiñosStateChanged

    private void jSpinnerIDsZonaEsperaPiscinaNiñosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsZonaEsperaPiscinaNiñosStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsZonaEsperaPiscinaNiños.getValue();
        p.mostrarIDSZonaEsperaPiscinaNiños(x);
    }//GEN-LAST:event_jSpinnerIDsZonaEsperaPiscinaNiñosStateChanged

    private void jSpinnerIDsColaPiscinaGrandeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaPiscinaGrandeStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsColaPiscinaGrande.getValue();
        p.mostrarIDSColaPiscinaGrande(x);
    }//GEN-LAST:event_jSpinnerIDsColaPiscinaGrandeStateChanged

    private void jSpinnerIDsZonaPiscinaGrandeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsZonaPiscinaGrandeStateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsZonaPiscinaGrande.getValue();
        p.mostrarIDSZonaPiscinaGrande(x);
    }//GEN-LAST:event_jSpinnerIDsZonaPiscinaGrandeStateChanged

    private void jSpinnerIDsColaPiscinaGrande1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaPiscinaGrande1StateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsColaPiscinaGrande1.getValue();
        p.mostrarIDSColaToboganA(x);
    }//GEN-LAST:event_jSpinnerIDsColaPiscinaGrande1StateChanged

    private void jSpinnerIDsColaPiscinaGrande2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaPiscinaGrande2StateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsColaPiscinaGrande2.getValue();
        p.mostrarIDSColaToboganB(x);
    }//GEN-LAST:event_jSpinnerIDsColaPiscinaGrande2StateChanged

    private void jSpinnerIDsColaPiscinaGrande3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerIDsColaPiscinaGrande3StateChanged
        // TODO add your handling code here:
        int x=(int) jSpinnerIDsColaPiscinaGrande3.getValue();
        p.mostrarIDSColaToboganC(x);
    }//GEN-LAST:event_jSpinnerIDsColaPiscinaGrande3StateChanged

    private void jTextFieldToboganCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToboganCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldToboganCActionPerformed

    private void jTextFieldToboganAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToboganAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldToboganAActionPerformed

    private void jTextFieldToboganBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToboganBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldToboganBActionPerformed

    private void jTextFieldMonitorToboganAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorToboganAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorToboganAActionPerformed

    private void jButtonPararReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararReanudarActionPerformed
        if(p.estadoParque()){
            jButtonPararReanudar.setText("PARAR");
            p.reanudarParque();
                
            }
            else{jButtonPararReanudar.setText("REANUDAR");
                    
                    p.pararParque();
                    
                    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPararReanudarActionPerformed

    private void jTextFieldMonitorVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorVActionPerformed

    private void jTextFieldMonitorPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorPOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorPOActionPerformed

    private void jTextFieldMonitorPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorPNActionPerformed

    private void jTextFieldMonitorTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorTBActionPerformed

    private void jTextFieldMonitorPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMonitorPGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMonitorPGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonPararReanudar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelColaEntrada;
    private javax.swing.JPanel jPanelColaPiscinaGrande;
    private javax.swing.JPanel jPanelColaPiscinaNiños;
    private javax.swing.JPanel jPanelColaPiscinaOlas;
    private javax.swing.JPanel jPanelColaTumbonas;
    private javax.swing.JPanel jPanelColaVestuario;
    private javax.swing.JPanel jPanelVestuario;
    private javax.swing.JPanel jPanelZonaPiscinaNiños;
    private javax.swing.JPanel jPanelZonaPiscinaOlas;
    private javax.swing.JPanel jPanelZonaTumbonas;
    private javax.swing.JPanel jPanelZonaTumbonas1;
    private javax.swing.JSpinner jSpinnerIDsColaEntrada;
    private javax.swing.JSpinner jSpinnerIDsColaPiscinaGrande;
    private javax.swing.JSpinner jSpinnerIDsColaPiscinaGrande1;
    private javax.swing.JSpinner jSpinnerIDsColaPiscinaGrande2;
    private javax.swing.JSpinner jSpinnerIDsColaPiscinaGrande3;
    private javax.swing.JSpinner jSpinnerIDsColaPiscinaNiños;
    private javax.swing.JSpinner jSpinnerIDsColaPiscinaOlas;
    private javax.swing.JSpinner jSpinnerIDsColaTumbonas;
    private javax.swing.JSpinner jSpinnerIDsColaVestuario;
    private javax.swing.JSpinner jSpinnerIDsVestuario;
    private javax.swing.JSpinner jSpinnerIDsZonaEsperaPiscinaNiños;
    private javax.swing.JSpinner jSpinnerIDsZonaPiscinaGrande;
    private javax.swing.JSpinner jSpinnerIDsZonaPiscinaNiños;
    private javax.swing.JSpinner jSpinnerIDsZonaPiscinaOlas;
    private javax.swing.JSpinner jSpinnerIDsZonaTumbonas;
    private javax.swing.JTextField jTextFieldConexiones;
    private javax.swing.JTextField jTextFieldMonitorPG;
    private javax.swing.JTextField jTextFieldMonitorPN;
    private javax.swing.JTextField jTextFieldMonitorPO;
    private javax.swing.JTextField jTextFieldMonitorTB;
    private javax.swing.JTextField jTextFieldMonitorToboganA;
    private javax.swing.JTextField jTextFieldMonitorToboganB;
    private javax.swing.JTextField jTextFieldMonitorToboganC;
    private javax.swing.JTextField jTextFieldMonitorV;
    private javax.swing.JTextField jTextFieldToboganA;
    private javax.swing.JTextField jTextFieldToboganB;
    private javax.swing.JTextField jTextFieldToboganC;
    private javax.swing.JTextField jTextIDsColaEntrada;
    private javax.swing.JTextField jTextIDsColaPiscinaGrande;
    private javax.swing.JTextField jTextIDsColaPiscinaGrande1;
    private javax.swing.JTextField jTextIDsColaPiscinaGrande2;
    private javax.swing.JTextField jTextIDsColaPiscinaGrande3;
    private javax.swing.JTextField jTextIDsColaPiscinaNiños;
    private javax.swing.JTextField jTextIDsColaPiscinaOlas;
    private javax.swing.JTextField jTextIDsColaTumbonas;
    private javax.swing.JTextField jTextIDsColaVestuario;
    private javax.swing.JTextField jTextIDsVestuario;
    private javax.swing.JTextField jTextIDsZonaEsperaPiscinaNiños;
    private javax.swing.JTextField jTextIDsZonaPiscinaGrande;
    private javax.swing.JTextField jTextIDsZonaPiscinaNiños;
    private javax.swing.JTextField jTextIDsZonaPiscinaOlas;
    private javax.swing.JTextField jTextIDsZonaTumbonas1;
    private java.awt.Panel panel1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
